# config.yml

version: "3.1"

assistant_id: "student_advisor_bot"

language: en

pipeline:
- name: spell_checker.SpellCheckerComponent
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "bert-base-uncased"
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "utter_fallback"
    enable_fallback_prediction: True
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
