[project]
name = "repl-nix-studentadvisorbot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.0.3",
    "flask-login>=0.6.3",
    "flask-sqlalchemy>=3.1.1",
    "rasa>=0.1.1",
    "spacy>=3.5.3",
    "werkzeug>=3.0.4",
]
